Project__Name: aws-fargate-bastion

AWS__Region: us-east-2

AWS__VPC__Availability_Zones:
  - us-east-2a 
  - us-east-2b 
  - us-east-2c
AWS__VPC__Cidr: 10.0.0.0/16
AWS__VPC__Public_Subnets:
  - 10.0.1.0/24
  - 10.0.2.0/24
  - 10.0.3.0/24
AWS__VPC__Private_Subnets:
  - 10.0.100.0/24
  - 10.0.101.0/24
  - 10.0.102.0/24